"""Generate the reference FLARE files used by the LAMMPS potential tests.

This script is NOT run by pytest. It documents how the committed reference potential was produced and
lets developers regenerate it (e.g. after a FLARE version bump). It trains a FLARE model on a single
crystalline Si8 configuration (energy only, zero forces) and writes, into this directory:

    flare_sgp.json         - the sparse GP (SGP_Wrapper.as_dict), read back by FlareSinglePointCalculator
    lammps_flare.flare     - the mapped LAMMPS pair coefficients
    mapped_unc_flare.flare - the mapped LAMMPS uncertainty coefficients
    flare.flare            - a human-readable marker listing the files above
    flare_provenance.json  - the training-set labels

Run it with the project environment active:  python generate_flare.py
"""

import json
import os
from pathlib import Path

import numpy as np
from flare.bffs.sgp.calculator import SGP_Calculator
from flare.utils import NumpyEncoder
from pymatgen.core import Lattice, Structure

from diffusion_for_multi_scale_molecular_dynamics.calc.base_single_point_calculator import \
    SinglePointCalculation
from diffusion_for_multi_scale_molecular_dynamics.mlip.flare.flare_configuration import \
    FlareConfiguration
from diffusion_for_multi_scale_molecular_dynamics.mlip.flare.flare_trainer import \
    FlareTrainer

OUTPUT_DIRECTORY = Path(__file__).parent

LATTICE_CONSTANT = 5.4437023699999996
CARTESIAN_POSITIONS = [
    [4.0827767774999995, 4.0827767774999995, 1.3609255924999999],
    [0.0, 2.7218511849999998, 2.7218511849999998],
    [4.0827767774999995, 1.3609255924999999, 4.0827767774999995],
    [0.0, 0.0, 0.0],
    [1.3609255924999999, 4.0827767774999995, 4.0827767774999995],
    [2.7218511849999998, 2.7218511849999998, 0.0],
    [1.3609255924999999, 1.3609255924999999, 1.3609255924999999],
    [2.7218511849999998, 0.0, 2.7218511849999998],
]
ENERGY = -26.371376

PAIR_COEFF_FILENAME = "lammps_flare.flare"
MAPPED_UNCERTAINTY_FILENAME = "mapped_unc_flare.flare"
TRAINING_LABEL = "crystalline_Si8"


def main():
    """Train the reference FLARE model and write its files into this directory."""
    structure = Structure(
        lattice=Lattice.cubic(LATTICE_CONSTANT),
        species=["Si"] * len(CARTESIAN_POSITIONS),
        coords=CARTESIAN_POSITIONS,
        coords_are_cartesian=True,
    )
    labelled_structure = SinglePointCalculation(
        calculation_type="reference",
        structure=structure,
        forces=np.zeros((len(structure), 3)),
        energy=ENERGY,
    )

    trainer = FlareTrainer(
        FlareConfiguration(cutoff=5.0, elements=["Si"], n_radial=8, lmax=3, variance_type="local")
    )
    trainer.add_labelled_structure(labelled_structure, active_environment_indices=list(range(len(structure))))
    trainer.fit()

    # Write every file into this directory. build_map writes into the current directory, so we run from here.
    os.chdir(OUTPUT_DIRECTORY)

    with open("flare_sgp.json", "w") as file:
        json.dump(trainer.sgp_model.as_dict(), file, cls=NumpyEncoder)

    SGP_Calculator(trainer.sgp_model, use_mapping=True).build_map(
        filename=PAIR_COEFF_FILENAME, contributor="generate_flare.py", map_uncertainty=True
    )
    os.replace(f"map_unc_{PAIR_COEFF_FILENAME}", MAPPED_UNCERTAINTY_FILENAME)

    with open("flare_provenance.json", "w") as file:
        json.dump([TRAINING_LABEL], file)

    with open("flare.flare", "w") as file:
        file.write(
            "# FLARE reference generated by generate_flare.py\n"
            "# SGP checkpoint : flare_sgp.json\n"
            f"# LAMMPS coeffs  : {PAIR_COEFF_FILENAME}\n"
            f"# Mapped unc     : {MAPPED_UNCERTAINTY_FILENAME}\n"
            "# Provenance     : flare_provenance.json\n"
        )


if __name__ == "__main__":
    main()
